// This file is auto-generated by `npm run cf-typegen` (wrangler types).
// It provides TypeScript types for your Worker's bindings (env vars, KV, R2, etc.).
// Run `npm run cf-typegen` after adding or renaming bindings in wrangler.jsonc.
// Commit this file so your team gets the same types without running the command.
//
// Until you run cf-typegen, this stub prevents TypeScript errors on "cloudflare:workers"
// imports. After running it, the generated file replaces this one.

interface Env {
  // Environment variables / secrets (set in Cloudflare Dashboard → Settings → Variables and Secrets)
  SUPABASE_SERVICE_ROLE_KEY: string;
  SUPABASE_PUBLISHABLE_KEY: string;
  VITE_SUPABASE_PUBLISHABLE_KEY: string;
  PESAPAL_CONSUMER_KEY: string;
  PESAPAL_CONSUMER_SECRET: string;
  PESAPAL_EMAIL: string;
  PESAPAL_ENV: string;
  CALLMEBOT_PHONE: string;
  CALLMEBOT_APIKEY: string;
  // Optional overrides
  PESAPAL_BASE_URL?: string;
  PESAPAL_IPN_URL?: string;
}
